### ISSUE TITLE
License for cdnjs

### ISSUE THREAD

**Issue by sashberd** [bkader/Dinakit#1]
Hi man,
We recently do an updates for all cdnjs hosted libraries licenses
The license of you library was not existed in documentation
Can the license that mentioned in you project be considered as MIT?
Thanks
Here ref to the question
https://github.com/cdnjs/cdnjs/pull/11847

**Comment by maruilian11** [comment]
Hi @bkader, Because we use `SPDX License List` as our license list, and we can't find DBAD License in this list. You don't have to do any modification, we just want to confirm if we can use MIT License for your lib on cdnjs. Thank you.
https://spdx.org/licenses/

**Comment by bkader** [comment]
Greetings,
Yes you can use MIT license.
Regards.

Sent using the mail.com mail app

**Comment by sashberd** [comment]
@maruilian11  This one stay without changes
